#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # ExportingEntityOrg
  # ---------------------------------------------------------------------------
  - Name: ExportingEntityOrg
    Domain: exportingentityorg.review.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
